services:

    Softlogo\ProductBundle\EventListener\ProductPreparer:
        tags:
            -
                name: 'doctrine.event_listener'
                # this is the only required option for the lifecycle listener tag
                event: 'prePersist'

                # listeners can define their priority in case multiple listeners are associated
                # to the same event (default priority = 0; higher numbers = listener is run earlier)
                priority: 500

                # you can also restrict listeners to a specific Doctrine connection
                connection: 'default'

    softlogo_product.admin.product:
        class: Softlogo\ProductBundle\Admin\ProductAdmin
        arguments: [~, Softlogo\ProductBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Shop, label: Products}

    softlogo_product.admin.category:
        class: Softlogo\ProductBundle\Admin\CategoryAdmin
        arguments: [~, Softlogo\ProductBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Shop, label: Categories}

    softlogo_product.admin.brand:
        class: Softlogo\ProductBundle\Admin\BrandAdmin
        arguments: [~, Softlogo\ProductBundle\Entity\Brand, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Shop, label: Brands, show_in_dashboard: false}

    softlogo_product.admin.product_media:
        class: Softlogo\ProductBundle\Admin\ProductMediaAdmin
        arguments: [~, Softlogo\ProductBundle\Entity\ProductMedia, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProductMedia, show_in_dashboard: false}

    softlogo_product.admin.product_parameter:
        class: Softlogo\ProductBundle\Admin\ProductParameterAdmin
        arguments: [~, Softlogo\ProductBundle\Entity\ProductParameter, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProductParameter, show_in_dashboard: false}
