<?php

namespace Softlogo\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function searchQuery($phrase){   
        $qb = $this->createQueryBuilder('a');
        //$qb->andWhere('o.aktywny = :aktywny')->setParameter('aktywny', 1);
        $qb->orWhere('a.name LIKE :phrase')
            ->setParameter('phrase', '%'.$phrase.'%');
        $qb->orWhere('a.description LIKE :phrase')
            ->setParameter('phrase', '%'.$phrase.'%');
		$query=$qb->getQuery();
		//echo $query->getSql();
        //return $query->getResult();
		return $query;
    }

    public function findByCategoryQuery($id){   
        $qb = $this->createQueryBuilder('a')->join('a.category', 'c');
        $qb->andWhere('c.id = :id')
            ->setParameter('id', $id);
		$query=$qb->getQuery();
		//echo $query->getSql();
        //return $query->getResult();
        return $query;
    }

    public function findAll(){   

		$dql   = "SELECT a FROM SoftlogoProductBundle:Product a";
		$query = $this->getEntityManager()->createQuery($dql);

		$query=$qb->getQuery();
		//echo $query->getSql();
        return $query->getResult();
    }



}
