product:
    path:     /
    defaults: { _controller: "SoftlogoProductBundle:Product:index" }

product_cat:
    path:  /products/category/{slug}
    defaults: { _controller: SoftlogoProductBundle:Product:findByCategory }

product_show:
    path:     /{cat_slug}/{slug}
    defaults: { _controller: "SoftlogoProductBundle:Product:show" }

product_garniture:
    path:     products/garniture/{cat}
    defaults: { _controller: "SoftlogoProductBundle:Product:garniture" }



product_search:
    path:     /search
    defaults: { _controller: "SoftlogoProductBundle:Search:index" }
